package codegen

import (
	"fmt"
	"strings"
)

// Рендер DTO. Один и тот же код печатается и для серверного пакета dto, и для
// пакета клиента — различается только имя пакета.

type buf struct {
	sb strings.Builder
}

func (b *buf) p(format string, args ...any) {
	if len(args) == 0 {
		b.sb.WriteString(format)
	} else {
		fmt.Fprintf(&b.sb, format, args...)
	}
	b.sb.WriteByte('\n')
}

func (b *buf) String() string { return b.sb.String() }

const genHeader = "// Code generated by babble. DO NOT EDIT."

func header(source, sum string) string {
	return fmt.Sprintf("%s\n// source: %s (sha256:%s)\n", genHeader, source, sum)
}

// RenderDTO печатает структуры контракта: поля, геттеры/сеттеры, UnmarshalJSON
// с учётом присутствия ключей, FillDefault_ и Validate_.
func RenderDTO(pkg string, m *Model, source, sum string) string {
	var b buf
	b.p("%s", header(source, sum))
	b.p("package %s", pkg)
	b.p("")
	b.p("import (")
	b.p("\t\"encoding/json\"")
	if m.UsesTime {
		b.p("\t\"time\"")
	}
	b.p("")
	b.p("\t\"github.com/mosdev-tech/babble\"")
	b.p(")")
	b.p("")

	for _, st := range m.Structs {
		renderStruct(&b, st)
	}

	// Ссылки на импорты, которые могут остаться неиспользованными в
	// вырожденных контрактах.
	b.p("var (")
	b.p("\t_ = json.Marshal")
	b.p("\t_ = babble.Field")
	if m.UsesTime {
		b.p("\t_ = time.Time{}")
	}
	b.p(")")
	return b.String()
}

func renderStruct(b *buf, st *Struct) {
	if st.Doc != "" {
		b.p("// %s %s", st.Name, st.Doc)
	}
	if st.OneOf {
		b.p("// Ровно один вариант может быть непустым (x-babble-oneof).")
	}
	b.p("type %s struct {", st.Name)
	for _, f := range st.Fields {
		line := fmt.Sprintf("\t%s %s %s", f.GoName, f.GoDecl(), f.Tag())
		if f.Doc != "" {
			line += " // " + strings.ReplaceAll(f.Doc, "\n", " ")
		}
		b.p("%s", line)
	}
	b.p("")
	b.p("\t// present_ помнит, какие ключи реально пришли в JSON: для")
	b.p("\t// обязательных полей отличить отсутствие от нулевого значения")
	b.p("\t// иначе невозможно.")
	b.p("\tpresent_ map[string]bool `json:\"-\"`")
	b.p("}")
	b.p("")

	renderAccessors(b, st)
	renderUnmarshal(b, st)
	renderOneOfConstructors(b, st)
	renderFillDefault(b, st)
	renderValidate(b, st)
}

func renderAccessors(b *buf, st *Struct) {
	for _, f := range st.Fields {
		t := f.Type.GoType
		if f.Ptr() {
			b.p("func (d *%s) Get%s() %s {", st.Name, f.GoName, t)
			b.p("\tif d == nil || d.%s == nil {", f.GoName)
			b.p("\t\tvar zero %s", t)
			b.p("\t\treturn zero")
			b.p("\t}")
			b.p("\treturn *d.%s", f.GoName)
			b.p("}")
			b.p("")
			b.p("func (d *%s) Set%s(v %s) { d.%s = &v }", st.Name, f.GoName, t, f.GoName)
		} else {
			b.p("func (d *%s) Get%s() %s {", st.Name, f.GoName, t)
			b.p("\tif d == nil {")
			b.p("\t\tvar zero %s", t)
			b.p("\t\treturn zero")
			b.p("\t}")
			b.p("\treturn d.%s", f.GoName)
			b.p("}")
			b.p("")
			b.p("func (d *%s) Set%s(v %s) { d.%s = v }", st.Name, f.GoName, t, f.GoName)
		}
		b.p("")
	}
}

func renderUnmarshal(b *buf, st *Struct) {
	b.p("func (d *%s) UnmarshalJSON(data []byte) error {", st.Name)
	b.p("\ttype alias %s", st.Name)
	b.p("\tvar a alias")
	b.p("\tif err := json.Unmarshal(data, &a); err != nil {")
	b.p("\t\treturn err")
	b.p("\t}")
	b.p("\tvar raw map[string]json.RawMessage")
	b.p("\tif err := json.Unmarshal(data, &raw); err != nil {")
	b.p("\t\treturn err")
	b.p("\t}")
	b.p("\t*d = %s(a)", st.Name)
	b.p("\td.present_ = make(map[string]bool, len(raw))")
	b.p("\tfor k, v := range raw {")
	b.p("\t\td.present_[k] = string(v) != \"null\"")
	b.p("\t}")
	b.p("\treturn nil")
	b.p("}")
	b.p("")
}

// renderOneOfConstructors: конструктор на вариант — единственный способ
// собрать сумму, не заполнив случайно два поля.
func renderOneOfConstructors(b *buf, st *Struct) {
	if !st.OneOf {
		return
	}
	for _, f := range st.Fields {
		b.p("func New%s%s(v %s) *%s {", st.Name, f.GoName, f.Type.GoType, st.Name)
		if f.Ptr() {
			b.p("\treturn &%s{%s: &v}", st.Name, f.GoName)
		} else {
			b.p("\treturn &%s{%s: v}", st.Name, f.GoName)
		}
		b.p("}")
		b.p("")
	}
}

func renderFillDefault(b *buf, st *Struct) {
	b.p("func (d *%s) FillDefault_(v *babble.Visitor) {", st.Name)
	b.p("\tif d == nil || !v.Enter(d) {")
	b.p("\t\treturn")
	b.p("\t}")
	for _, f := range st.Fields {
		if f.Default != nil && f.Ptr() {
			lit, ok := defaultLiteral(f)
			if ok {
				b.p("\tif d.%s == nil {", f.GoName)
				b.p("\t\tdv := %s", lit)
				b.p("\t\td.%s = &dv", f.GoName)
				b.p("\t}")
			}
		}
		fillNested(b, f)
	}
	b.p("}")
	b.p("")
}

func fillNested(b *buf, f *Field) {
	switch f.Type.Kind {
	case KindStruct:
		if f.Ptr() {
			b.p("\td.%s.FillDefault_(v)", f.GoName)
		} else {
			b.p("\t(&d.%s).FillDefault_(v)", f.GoName)
		}
	case KindArray:
		if f.Type.Elem.Kind == KindStruct {
			b.p("\tfor i := range d.%s {", f.GoName)
			b.p("\t\t(&d.%s[i]).FillDefault_(v)", f.GoName)
			b.p("\t}")
		}
	case KindMap:
		if f.Type.Elem.Kind == KindStruct {
			b.p("\tfor k := range d.%s {", f.GoName)
			b.p("\t\tmv := d.%s[k]", f.GoName)
			b.p("\t\t(&mv).FillDefault_(v)")
			b.p("\t\td.%s[k] = mv", f.GoName)
			b.p("\t}")
		}
	}
}

func defaultLiteral(f *Field) (string, bool) {
	switch f.Type.Kind {
	case KindString:
		s, ok := f.Default.(string)
		if !ok {
			return "", false
		}
		return fmt.Sprintf("%q", s), true
	case KindEnum:
		s, ok := f.Default.(string)
		if !ok {
			return "", false
		}
		return fmt.Sprintf("%s(%q)", f.Type.GoType, s), true
	case KindBool:
		v, ok := f.Default.(bool)
		if !ok {
			return "", false
		}
		return fmt.Sprintf("%t", v), true
	case KindInt64, KindInt32:
		switch v := f.Default.(type) {
		case int:
			return fmt.Sprintf("%s(%d)", f.Type.GoType, v), true
		case float64:
			return fmt.Sprintf("%s(%d)", f.Type.GoType, int64(v)), true
		}
		return "", false
	case KindFloat64, KindFloat32:
		switch v := f.Default.(type) {
		case int:
			return fmt.Sprintf("%s(%d)", f.Type.GoType, v), true
		case float64:
			return fmt.Sprintf("%s(%v)", f.Type.GoType, v), true
		}
		return "", false
	default:
		return "", false
	}
}

func renderValidate(b *buf, st *Struct) {
	b.p("func (d *%s) Validate_(v *babble.Visitor, path string) error {", st.Name)
	b.p("\tif d == nil || !v.Enter(d) {")
	b.p("\t\treturn nil")
	b.p("\t}")

	for _, f := range st.Fields {
		if f.Required {
			b.p("\tif err := babble.CheckRequired(babble.Field(path, %q), d.present_ == nil || d.present_[%q]); err != nil {", f.JSONTag, f.JSONTag)
			b.p("\t\treturn err")
			b.p("\t}")
		}
	}

	for _, f := range st.Fields {
		if !f.Type.NeedsValidation() {
			continue
		}
		fieldPath := fmt.Sprintf("babble.Field(path, %q)", f.JSONTag)
		switch {
		case f.Ptr():
			b.p("\tif d.%s != nil {", f.GoName)
			renderChecks(b, "\t\t", "(*d."+f.GoName+")", "d."+f.GoName, fieldPath, f.Type)
			b.p("\t}")
		case f.Optional():
			// Срез или карта: nil означает «не задано», проверять нечего.
			b.p("\tif d.%s != nil {", f.GoName)
			renderChecks(b, "\t\t", "d."+f.GoName, "&d."+f.GoName, fieldPath, f.Type)
			b.p("\t}")
		default:
			renderChecks(b, "\t", "d."+f.GoName, "&d."+f.GoName, fieldPath, f.Type)
		}
	}

	if st.OneOf {
		b.p("\tvar set_ []string")
		for _, f := range st.Fields {
			if f.Ptr() {
				b.p("\tif d.%s != nil {", f.GoName)
			} else {
				b.p("\t{")
			}
			b.p("\t\tset_ = append(set_, %q)", f.JSONTag)
			b.p("\t}")
		}
		b.p("\tif err := babble.CheckOneOf(path, set_); err != nil {")
		b.p("\t\treturn err")
		b.p("\t}")
	}

	b.p("\treturn nil")
	b.p("}")
	b.p("")
}

// renderChecks печатает проверки для значения value (типа t) с путём pathExpr.
// addr — выражение указателя на то же значение, нужно для вложенных структур.
func renderChecks(b *buf, indent, value, addr, pathExpr string, t *TypeRef) {
	c := t.C
	num := func(fn string, lit string) {
		b.p("%sif err := babble.%s(%s, %s, %s(%s)); err != nil {", indent, fn, pathExpr, value, t.GoType, lit)
		b.p("%s\treturn err", indent)
		b.p("%s}", indent)
	}

	switch t.Kind {
	case KindString, KindEnum:
		if c.MinLength != nil {
			b.p("%sif err := babble.CheckMinLength(%s, string(%s), %d); err != nil {", indent, pathExpr, value, *c.MinLength)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
		if c.MaxLength != nil {
			b.p("%sif err := babble.CheckMaxLength(%s, string(%s), %d); err != nil {", indent, pathExpr, value, *c.MaxLength)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
		if c.Pattern != "" {
			b.p("%sif err := babble.CheckPattern(%s, string(%s), %q); err != nil {", indent, pathExpr, value, c.Pattern)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
		if t.Kind == KindEnum {
			b.p("%sif err := babble.CheckEnum(%s, %s, %s_All); err != nil {", indent, pathExpr, value, t.EnumName)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
	case KindInt64, KindInt32, KindFloat64, KindFloat32:
		if c.Minimum != nil {
			num("CheckMinimum", formatNumber(t.Kind, *c.Minimum))
		}
		if c.Maximum != nil {
			num("CheckMaximum", formatNumber(t.Kind, *c.Maximum))
		}
	case KindStruct:
		b.p("%sif err := %s.Validate_(v, %s); err != nil {", indent, addr, pathExpr)
		b.p("%s\treturn err", indent)
		b.p("%s}", indent)
	case KindArray, KindMap:
		if c.MinItems != nil {
			b.p("%sif err := babble.CheckMinItems(%s, len(%s), %d); err != nil {", indent, pathExpr, value, *c.MinItems)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
		if c.MaxItems != nil {
			b.p("%sif err := babble.CheckMaxItems(%s, len(%s), %d); err != nil {", indent, pathExpr, value, *c.MaxItems)
			b.p("%s\treturn err", indent)
			b.p("%s}", indent)
		}
		if !t.Elem.NeedsValidation() {
			return
		}
		if t.Kind == KindArray {
			b.p("%sfor i_ := range %s {", indent, value)
			elemPath := fmt.Sprintf("babble.Index(%s, i_)", pathExpr)
			renderChecks(b, indent+"\t", fmt.Sprintf("%s[i_]", value), fmt.Sprintf("&%s[i_]", value), elemPath, t.Elem)
			b.p("%s}", indent)
		} else {
			b.p("%sfor k_, e_ := range %s {", indent, value)
			elemPath := fmt.Sprintf("babble.Key(%s, k_)", pathExpr)
			renderChecks(b, indent+"\t", "e_", "&e_", elemPath, t.Elem)
			b.p("%s}", indent)
		}
	}
}

func formatNumber(k Kind, v float64) string {
	switch k {
	case KindInt64, KindInt32:
		return fmt.Sprintf("%d", int64(v))
	default:
		return fmt.Sprintf("%v", v)
	}
}

// RenderConst печатает enum'ы: именованный строковый тип, консты, список
// допустимых значений и Valid().
func RenderConst(pkg string, m *Model, source, sum string) string {
	var b buf
	b.p("%s", header(source, sum))
	b.p("package %s", pkg)
	b.p("")

	for _, e := range m.Enums {
		b.p("type %s string", e.Name)
		b.p("")
		b.p("const (")
		for _, v := range e.Values {
			b.p("\t%s %s = %q", v.ConstName, e.Name, v.Value)
		}
		b.p(")")
		b.p("")
		b.p("var %s_All = []%s{", e.Name, e.Name)
		for _, v := range e.Values {
			b.p("\t%s,", v.ConstName)
		}
		b.p("}")
		b.p("")
		b.p("func (v %s) Valid() bool {", e.Name)
		b.p("\tfor _, a := range %s_All {", e.Name)
		b.p("\t\tif a == v {")
		b.p("\t\t\treturn true")
		b.p("\t\t}")
		b.p("\t}")
		b.p("\treturn false")
		b.p("}")
		b.p("")
		b.p("func (v %s) String() string { return string(v) }", e.Name)
		b.p("")
	}
	return b.String()
}
