version: "3"

tasks:
  codegen:
    desc: "Кодоген: сервер, стабы, клиенты"
    cmds:
      - go run github.com/mosdev-tech/babble/cmd/babble gen
    silent: true
  lint:
    desc: "Линт контрактов по правилам профиля rpc"
    cmds:
      - go run github.com/mosdev-tech/babble/cmd/babble lint
  fmt:
    cmds:
      - go fmt ./...
    silent: true
  test:
    cmds:
      - go test ./...
  run:
    desc: "Запуск сервиса"
    dotenv: [".env"]
    cmds:
      - go run ./cmd/service
